pipeline {
	agent any
	stages {
		stage('preparation') {
			steps {
				echo 'preparation started--------------------'

				script {
					if (isUnix()) {
						sh 'echo "unix command"'
					} else {
						bat(/echo "windows command"/)
					}
				}
				
				echo 'preparation ended.'
			}
		}
		stage('build') {
			steps {
				echo 'build started--------------------'

				echo 'build ended.'
			}
		}
		stage('config') {
			steps {
				echo 'config started--------------------'
				
				script {	
					if (isUnix()) {
						sh '''
							mkdir -p ${env.WORKSPACE}/content-replace/env/prd
							cp ${env.WORKSPACE}/content-replace/conf.properties ${env.WORKSPACE}/content-replace/env/prd
						'''
					} else {
						bat(/echo "windows command/)
					}
				}
				contentReplace( 
					configs: [ 
						fileContentReplaceConfig( 
							configs: [ 
								fileContentReplaceItemConfig(search: '#\\{conf\\.server\\.name\\}#', replace: 'HQvsCRMAPP01', matchCount: 1) 
							],
							fileEncoding: 'UTF-8', 
							filePath: '${env.WORKSPACE}/content-replace/env/prd/conf.properties'
						) 
					]
				)

				echo 'config ended.'
			}
		}
		stage('results') {
			steps {
				echo 'results started--------------------'

				//junit '**/target/surefire-reports/TEST-*.xml'
				//archiveArtifacts 'target/*.jar

				echo 'results ended.'
			}
		}
	}
}
